-- Create the table
CREATE TABLE IF NOT EXISTS "rides" (
    "id" INTEGER,
    "origin" TEXT NOT NULL,
    "destination" TEXT NOT NULL,
    "rider" TEXT NOT NULL,
    PRIMARY KEY("id")
);

-- Insert 78 sample data entries
INSERT INTO "rides" ("id", "origin", "destination", "rider") VALUES
(1, 'New York', 'Boston', 'John Smith'),
(2, 'Los Angeles', 'San Francisco', 'Emma Johnson'),
(3, 'Chicago', 'Detroit', 'Michael Brown'),
(4, 'Houston', 'Dallas', 'Sarah Davis'),
(5, 'Phoenix', 'Tucson', 'James Wilson'),
(6, 'Philadelphia', 'Washington DC', 'Linda Martinez'),
(7, 'San Antonio', 'Austin', 'Robert Anderson'),
(8, 'San Diego', 'Los Angeles', 'Maria Taylor'),
(9, 'Dallas', 'Houston', 'David Thomas'),
(10, 'San Jose', 'San Francisco', 'Jennifer Jackson'),
(11, 'Austin', 'San Antonio', 'Charles White'),
(12, 'Jacksonville', 'Miami', 'Patricia Harris'),
(13, 'Fort Worth', 'Dallas', 'Thomas Martin'),
(14, 'Columbus', 'Cleveland', 'Margaret Thompson'),
(15, 'Charlotte', 'Raleigh', 'Christopher Garcia'),
(16, 'San Francisco', 'San Jose', 'Elizabeth Robinson'),
(17, 'Indianapolis', 'Chicago', 'William Clark'),
(18, 'Seattle', 'Portland', 'Susan Rodriguez'),
(19, 'Denver', 'Colorado Springs', 'Daniel Lewis'),
(20, 'Washington DC', 'Baltimore', 'Jessica Lee'),
(21, 'Boston', 'New York', 'Mark Walker'),
(22, 'El Paso', 'Albuquerque', 'Sarah Hall'),
(23, 'Detroit', 'Chicago', 'Paul Allen'),
(24, 'Nashville', 'Memphis', 'Karen Young'),
(25, 'Memphis', 'Nashville', 'Steven King'),
(26, 'Portland', 'Seattle', 'Nancy Wright'),
(27, 'Oklahoma City', 'Tulsa', 'Edward Scott'),
(28, 'Las Vegas', 'Los Angeles', 'Donna Torres'),
(29, 'Baltimore', 'Washington DC', 'Kenneth Nguyen'),
(30, 'Milwaukee', 'Chicago', 'Lisa Hill'),
(31, 'Albuquerque', 'El Paso', 'George Adams'),
(32, 'Tucson', 'Phoenix', 'Betty Nelson'),
(33, 'Fresno', 'Los Angeles', 'Kevin Carter'),
(34, 'Sacramento', 'San Francisco', 'Helen Mitchell'),
(35, 'Kansas City', 'St. Louis', 'Brian Perez'),
(36, 'Miami', 'Orlando', 'Deborah Roberts'),
(37, 'Raleigh', 'Charlotte', 'Ronald Turner'),
(38, 'Omaha', 'Kansas City', 'Carol Phillips'),
(39, 'Minneapolis', 'Chicago', 'Jason Campbell'),
(40, 'Tulsa', 'Oklahoma City', 'Michelle Parker'),
(41, 'New Orleans', 'Baton Rouge', 'Gary Evans'),
(42, 'Cleveland', 'Columbus', 'Amanda Edwards'),
(43, 'St. Louis', 'Kansas City', 'Frank Collins'),
(44, 'Pittsburgh', 'Philadelphia', 'Melissa Stewart'),
(45, 'Cincinnati', 'Indianapolis', 'Raymond Morris'),
(46, 'Anaheim', 'Los Angeles', 'Cynthia Murphy'),
(47, 'Toledo', 'Detroit', 'Walter Cook'),
(48, 'Buffalo', 'Rochester', 'Kathleen Rogers'),
(49, 'St. Paul', 'Minneapolis', 'Arthur Morgan'),
(50, 'Corpus Christi', 'San Antonio', 'Janet Peterson'),
(51, 'Colorado Springs', 'Denver', 'Billy Cooper'),
(52, 'Aurora', 'Denver', 'Doris Bailey'),
(53, 'Rochester', 'Buffalo', 'Joe Reed'),
(54, 'Arlington', 'Dallas', 'Jacqueline Ward'),
(55, 'Baton Rouge', 'New Orleans', 'Albert Cox'),
(56, 'Richmond', 'Washington DC', 'Joyce Howard'),
(57, 'Boise', 'Salt Lake City', 'Henry Bell'),
(58, 'Spokane', 'Seattle', 'Diane Foster'),
(59, 'Des Moines', 'Omaha', 'Carl Gray'),
(60, 'Madison', 'Milwaukee', 'Martha Powell'),
(61, 'Bridgeport', 'New York', 'Eugene Sullivan'),
(62, 'Salt Lake City', 'Boise', 'Ruth James'),
(63, 'Syracuse', 'Buffalo', 'Ralph Hayes'),
(64, 'Huntsville', 'Nashville', 'Frances Bryant'),
(65, 'Wichita', 'Kansas City', 'Lawrence Alexander'),
(66, 'Houston', 'San Antonio', 'Lillian Russell'),
(67, 'Little Rock', 'Memphis', 'Phillip Griffin'),
(68, 'Mobile', 'New Orleans', 'Diana Diaz'),
(69, 'Jackson', 'Memphis', 'Adam Hayes'),
(70, 'Knoxville', 'Nashville', 'Gloria Myers'),
(71, 'Dayton', 'Cincinnati', 'Sean Ford'),
(72, 'Aurora', 'Chicago', 'Cheryl Reynolds'),
(73, 'Springfield', 'St. Louis', 'Austin Pierce'),
(74, 'Grand Rapids', 'Detroit', 'Emily Chavez'),
(75, 'Akron', 'Cleveland', 'Jonathan Bennett'),
(76, 'Montgomery', 'Mobile', 'Shirley Fisher'),
(77, 'Tallahassee', 'Jacksonville', 'Dennis Morris'),
(78, 'Hialeah', 'Miami', 'Julia Peterson');